all: cuts

cuts: cuts.o filter.o modulation.o demodulation.o
	i686-w64-mingw32-gcc -o cuts cuts.o filter.o modulation.o demodulation.o -lm

cuts.o: cuts.c wavmeta.h wavschema.h filter.h modulation.h demodulation.h
	i686-w64-mingw32-gcc -c cuts.c
	
filter.o: filter.c filter.h
	i686-w64-mingw32-gcc -c filter.c 

modulation.o: modulation.c modulation.h
	i686-w64-mingw32-gcc -c modulation.c

demodulation.o: demodulation.c demodulation.h
	i686-w64-mingw32-gcc -c demodulation.c

clean:
	rm -f *.o
